# Generated by Django 4.2 on 2025-05-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_rename_phone_user_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
