# Generated by Django 4.2 on 2025-05-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_wishlist_remove_cartorderitem_vendor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptin',
            new_name='description',
        ),
    ]
