# Generated by Django 4.2 on 2025-05-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_descriptin_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='produt',
            new_name='product',
        ),
    ]
