# Generated by Django 4.2 on 2025-05-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['country'], 'verbose_name_plural': 'Taxes'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shipping_cost',
            new_name='shipping_amount',
        ),
    ]
