# Generated by Django 4.2 on 2025-06-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_notification_user_alter_notification_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('fullflled', 'Fullfilled'), ('cancelled', 'Caneclled')], default='pending', max_length=100),
        ),
    ]
