# Generated by Django 4.2 on 2025-06-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_cartorder_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
