# Setup phase: Install system dependencies
[phases.setup]
  nixPkgs = ['python312', 'gcc', 'libpq']  # Python 3.12, GCC, and Postgres dev libraries
  aptPkgs = []  # Additional apt packages not required

# Install phase: Install Python dependencies
[phases.install]
  cmds = ['pip install -r requirements.txt']

# Build phase: Prepare the static files
[phases.build]
  cmds = [
    'python manage.py collectstatic --noinput'  # Optional cache-busting
  ]

# Start phase: Run the application
[start]
  cmd = 'gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --log-file -'
